version: "3.8"

services:
  db-postgres:
    image: postgres:15-alpine
    container_name: "db-postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  db-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "pg-admin"
    restart: always
    depends_on:
      - db-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
networks:
  default:
    name: local-network
    external: true